---
# ------------------ Software Installation -----------------------
- name: install jenkins dependencies on CentOS
  become: true
  tags: jenkins, centos
  yum: 
    name: 
      - epel-release
      - java-11-openjdk-devel
      - git
        #:- '{{ jenkins_centos_bin }}'

        #- name: start virtualization service
        #  become: true
        #systemd:
        #name: jenkins
        #enabled: yes
        #state: started
