---
# ------------------ Software Installation -----------------------
- name: install jenkins dependencies on CentOS
  become: true
  tags: jenkins, centos
  yum: 
    name: 
      - epel-release
      - java-11-openjdk-devel
      - git
