---
# ------------------ CentOS packages -----------------------
- name: downloading jenkins for centos
  become: true
  tags: jenkins, Centos
  get_url:
    url: '{{ jenkins_centos_bin }}'
    dest: '{{ jenkins_install_dir_centos }}'
    force: yes
    mode: 0755

- name: downloading jenkins key for centos
  become: true
  tags: jenkins, CentOS
  rpm_key:
    key: '{{ jenkins_key_centos }}'
    state: present

# ------------------ Software Installation -----------------------
- name: install jenkins & dependencies on CentOS
  become: true
  tags: jenkins, centos
  yum: 
    name: 
      - epel-release
      - java-11-openjdk-devel
      - jenkins