# ------------------ Software Installation -----------------------
- name: install jenkins & dependencies on CentOS
  become: true
  tags: jenkins
  yum: 
    name: 
      - epel-release
      - java-11-openjdk-devel
      - jenkins
  when: ansible_distribution == "CentOS"

- name: install jenkins  for Ubuntu
  tags: jenkins
  apt: 
    - jenkins

  when: ansible_distribution == "Ubuntu"  
# ------------------- Starting Services -----------------------
- name: reloading daemon
  become: true
  systemd:
    daemon-reload: yes