---
- name: Fetch /etc/os-release
  raw: cat /etc/os-release
  register: os_release
  changed_when: false
  # This command should always run, even in check mode
  check_mode: false
  environment: {}

- include_tasks: jenkins-centos.yml
  when: '"CentOS" in os_release.stdout or "Red Hat Enterprise Linux" in os_release.stdout or "Oracle" in os_release.stdout'

- include_tasks: jenkins-debian.yml
  when: '"Debian" in os_release.stdout or "Ubuntu" in os_release.stdout'

# ------------------- Starting Services -----------------------
- name: reloading daemon
  become: true
  systemd:
    daemon-reload: yes