---
# ------------------ Updating package managers ---------------------- 
- name: install updates for CentOS
  tags: always
  yum: 
    update_only: yes
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: install updates for Ubuntu
  tags: always
  apt: 
    update_only: yes
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# ------------------- Software Download -----------------------
- name: downloading minikube
  become: true
  tags: minikube
  get_url:
    url: '{{ minikube_url }}'
    dest: '{{ minikube_install_target }}'
    mode: 0755

- name: downloading kubectl
  become: true
  tags: kubectl
  get_url:
    url: '{{ kubectl_url }}'
    dest: '{{ kubectl_install_target }}'
    mode: 0755
# ------------------ Software Installation -----------------------
- name: install minikube kvm drivers
  become: true
  tags: minikube
  yum: 
    name: 
      - libvirt
      - qemu-kvm
      - libvirt-python
      - libguestfs-tools
      - bridge-utils

# - name: installing minikube
#   become: true
#   tags: minikube
#   command: install {{ minikube_install_target }} {{ minikube_install_link }}
# ------------------- Starting Services & Minikube -----------------------
- name: start virtualization service
  become: true
  service:
    name: libvirtd
    state: started
   
- name: Starting minikube
  tags: minikube
  command: minikube start