---
# ------------------ Updating package managers ---------------------- 
- name: install updates for debian
  become: true
  apt: 
    update_only: yes
    update_cache: yes

# ------------------ Software Installation -----------------------
 
    
- name: Install helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
    dest: /usr/local/bin/helm
    remote_src: yes
    