---
# ------------------ Updating package managers ---------------------- 
- name: install updates for CentOS
  become: true
  yum: 
    update_only: yes
    update_cache: yes

# ------------------ Software Installation -----------------------
- name: install yum utils
  become: true
  tags: minikube
  yum: 
    name:
      - yum-utils  
    
- name: Install helm
  ansible.builtin.unarchive:
    src: https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
    dest: /usr/local/bin/helm
    remote_src: yes

