---
# ------------------ Updating package managers ---------------------- 
- name: install updates for CentOS
  become: true
  yum: 
    update_only: yes
    update_cache: yes

# ------------------ Software Installation -----------------------
- name: install yum utils
  become: true
  tags: minikube
  yum: 
    name:
      - yum-utils  
    


