---
# tasks file for ansible-role
- name: install updates for CentOS
  tags: always
  yum: 
    update_only: yes
    update_cache: yes

- name: downloading minikube
  become: yes
  tags: minikube
  become_user: root
  get_url:
    url: '{{ minikube_url }}'
    dest: '{{ minikube_install_target }}'
    checksum: '{{ minikube_checksum }}'
    mode: 0755

- name: linking {{ minikube_install_link }} to {{ minikube_install_target }}
  become: yes
  tags: minikube
  become_user: root
  file:
    src: '{{ minikube_install_target }}'
    dest: '{{ minikube_install_link }}'
    state: link
