---
# tasks file for ansible-role
- name: install updates for CentOS
  tags: always
  yum: 
    update_only: yes
    update_cache: yes
  when: ansible_distribution==CentOS
 
- name: install update for Ubuntu
  tags: always
  apt: 
    update_only: yes
    update_cache: yes
  when: ansible_distribution==Ubuntu
  
- name: downloading minikube
  become: yes
  tags: minikube
  get_url:
    url: '{{ minikube_url }}'
    dest: '{{ minikube_install_target }}'
    mode: 0755

- name: linking {{ minikube_install_link }} to {{ minikube_install_target }}
  become: yes
  tags: minikube
  file:
    src: '{{ minikube_install_target }}'
    dest: '{{ minikube_install_target }}'
    state: link

- name: installing minikube
  become: yes
  tags: minikube
  command: install minikube-{{ minikube_os }}-{{ minikube_arch }} {{ minikube_install_target }}