---
# tasks file for ansible-role
- name: install updates for CentOS
  tags: always
  yum: 
    update_only: yes
    update_cache: yes

- name: downloading minikube
  become: yes
  tags: minikube
  get_url:
    url: '{{ minikube_url }}'
    dest: '{{ minikube_install_target }}'
    mode: 0755

    #- name: linking {{ minikube_install_link }} to {{ minikube_install_target }}
    #become: yes
    #become_user: root
    #tags: minikube
    #file:
    #src: '{{ minikube_install_target }}'
    #dest: '{{ minikube_install_target }}'
    #state: link
- name: install minikube kvm drivers
  become: yes
  tags: minikube
  yum: 
    name: 
      - libvirt
      - qemu-kvm
      - libvirt-python
      - libguestfs-tools
      - bridge-utils
      
- name: installing minikube
  become: yes
  tags: minikube
  command: sudo install {{ minikube_install_target }} {{ minikube_install_link }}
