---
# ----------------------- versions ------------------------
jenkins_version: 2.289.2.2-1.1

# ----------------------- ubuntu ------------------------
jenkins_target_file: /etc/apt/sources.list.d/jenkins.list
jenkins_ubuntu_bin: https://pkg.jenkins.io/debian-stable binary/
jenkins_key_ubuntu: https://pkg.jenkins.io/debian-stable/jenkins.io.key