apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-pv-claim
  namespace: warehouse-ns
  labels:
    app: warehouse-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi